### ISSUE TITLE
Basic: Reduce output not passing.

### ISSUE THREAD

**Issue by deepfelt** [timoxley/functional-javascript-workshop#112]
Can you tell me why my code isn't passing?  It returns an object with the correct keys and values, but they are not in the same order as in the expected result.
here is my code:

    function countWords(inputWords) {
		var result = {};
		inputWords.reduce(function(a, b){
				if (!result[b]){
						result[b] = 1;
				}
				else {
						result[b] = result[b] +1;
				}
			})
			return result;
    }
    module.exports = countWords;

Thanks!

**Comment by ethangodt** [comment]
Hey! I thought I'd chime in because this workshop has helped me so much in the past.

Your answer is actually not the same as the expected. Check the first key from the *expected* result within *your* list — in your object it won't be first, and it will be counted one fewer times than it should have been. Everything else is in the correct order; this means that you probably forgot to count the very first word.

This is happening because of the way the reduce function works. It can take two arguments: 1. the accumulator function that you're using to summarize the data, 2. the initial value to start accumulating to (i.e. what the value of 'a' is on the first iteration). If you don't include the optional initial value argument then the function will automatically take the first element from the array as the value of 'a' and then start iterating from the second elem. So, for you, this means that your function is taking the first word as the value of 'a' the first iteration through (b/c you are not passing the optional arg), and then is looping through all the values starting with the second. Therefore, the first word is just being forgotten.

Lastly, there is a better way to use reduce here. Essentially, you could accomplish your strategy of declaring the result object outside of the function and then adding to it better with a for loop or forEach loop. With reduce, you want to do all the accumulating within the function. You should set the initial value to be an empty object (so you don't skip the first word), then return that object after each time you add something to it (so it becomes the value of 'a' each iteration), and then your reduce function will return that finished object at the end.

Sorry for the novel... here is the code:

```
function countWords(inputWords) {
    // var result = {}; delete this here
    return inputWords.reduce(function(a, b){ // added return here for when the whole reduce function returns the finished object
            if (!a[b]){
                    a[b] = 1;
            }
            else {
                    a[b] = a[b] + 1;
            }
            return a; // whatever is return each iteration become the value of 'a' the next iteration
        }, {}); // added an empty object as the initial value - now 'a' is empty object the first time through instead of the first word
        // return result; delete this
}
module.exports = countWords;
```

Here is a link to my solutions to the challenges with some explanation if you get stumped like this on any others — feel free to suggest changes that might make them better:
https://github.com/ethangodt/nodeschool-solutions/tree/master/functional-javascript

**Comment by timoxley** [comment]
@ethangodt wow nice writeup.

**Comment by timoxley** [comment]
Not sure if giving solutions like that should come with a spoiler alert though, since a lot of the solid understanding comes from figuring out out yourself for the first time.

**Comment by ethangodt** [comment]
@timoxley Agree. I'll add a comment at the top. Let me know if there is a better way to do this.

Btw, thanks so much for looking over these challenges. They've helped me a lot.

**Comment by deepfelt** [comment]
Thanks, @ethangodt  I appreciate the explanation, and see where I went wrong. 
Also, thank you @timoxley  for setting up these challenges.  They are very helpful.
