### ISSUE TITLE
Function Spies: preservation of 'this'

### ISSUE THREAD

**Issue by stkb** [timoxley/functional-javascript-workshop#39]
In the Function Spies exercise the official solution is:

```
function Spy(target, method) {
    var originalFunction = target[method]
    var result = {
      count: 0
    }

    target[method] = function() {
      result.count++
      return originalFunction.apply(target, arguments)
    }

    return result
  }

  module.exports = Spy
```

Isn't it better to have the 9th line as `return originalFunction.apply(this, arguments)` instead, to preserve the 'this' context in case the spied-on method might be called by unconventional means (call/apply etc)?

**Comment by kierans** [comment]
@samjewell It would be whatever the "this" argument is when the spying function is applied/called.  From the test code in the lesson

    var parent = {
      test: function() {
        // ... code ommitted 
        return arguments
      }
    }

    var originalFn = parent.test.bind(parent)
    var spy = Spy(parent, 'test')
  
    input.forEach(function(args, i) {
      // ... code ommitted      
      assert.deepEqual(originalFn.apply(parent, args), parent.test.apply(parent, args), "Check your function's return value!")
    })

In this case the ```this``` of ```return originalFunction.apply(this, arguments)``` would be ```parent``` which in this example would be the same as the ```target``` argument since we create the spy like so ```var spy = Spy(parent, 'test')```

**Comment by kierans** [comment]
@timoxley I think leaving the ```this``` parameter to ```target``` is correct.  Consider the following.

    var life = {
      determineMeaningOfLife: function() {
        this.meaningOfLife = 42;
      },
    
      whatIsTheMeaningOfLife: function() {
        console.log("The meaning of life is:", this.meaningOfLife);
      }
    };
    
    var afterlife = {};
    
    var spy = Spy(life, "determineMeaningOfLife");
    
    life.determineMeaningOfLife.apply(afterlife);
    
    life.whatIsTheMeaningOfLife();
    console.log("Method called %d times. ", spy.count);

The output is:

    The meaning of life is: undefined
    Method called 1 times.

I think that function spies should always operate in the context of the target, because we're wanting to decorate the behaviour of the existing function, not alter it.

The need to ```apply()``` the spied function with a ```this``` arg is an unfortunate quirk of JS when using a variable number of arguments such as the original test code, however we should always apply/call spies in the the context of the target.  Consider a function on a target object that takes named parameters.  There would be no need to apply/call the function with a ```this``` argument, thus the behaviour of the invocation of the spy is always correct.  For example:

    life.overrideMeaningOfLife = function(meaning) {
      this.meaningOfLife = meaning;
    };

    life.overrideMeaningOfLife("My philosophy");
    
    var spy = Spy(life, "overrideMeaningOfLife");

    life.whatIsTheMeaningOfLife();
    console.log("Method called %d times. ", spy.count);

    The meaning of life is: My philosophy
    Method called 1 times.

In the above case, ```return originalFunction.apply(this, arguments)``` would be OK since ```this === target```.  However for the spy to __guarantee__ correct behaviour it should explicity use ```target``` not ```this```

Therefore ```return originalFunction.apply(target, arguments)``` is the correct solution IMHO.
